name: Python CD

on:
  workflow_run:
    workflows: [ "Python CI" ]
    types:
      - completed
    branches:
      - main-clean

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if passworder_core.py changed
        id: check_changes
        run: |
          git fetch origin main-clean
          changed=$(git diff --name-only origin/main-clean $GITHUB_SHA | grep 'passworder/passworder_core.py' || true)
          if [ -n "$changed" ]; then
            echo "core_changed=true" >> $GITHUB_OUTPUT
          else
            echo "core_changed=false" >> $GITHUB_OUTPUT

      - name: Debug filter
        run: echo "changed = ${{ steps.check_changes.outputs.core_changed }}"

      - name: Deploy steps
        if: steps.check_changes.outputs.core_changed == 'true'
        run: |
          echo "Deploying because passworder_core.py changed!"
          python -m pip install --upgrade pip
          python version_bump.py
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add passworder/__init__.py
          git commit -m "Bump patch version [skip ci]" || echo "No changes to commit"
          git pull --rebase
          git push origin main-clean
          python -m pip install --upgrade build twine
          python -m build
          python -m twine upload dist/* \
            --username __token__ \
            --password ${{ secrets.PYPI_TOKEN }}