name: Version Bump

on:
  push:
    branches: [ main-clean ]

jobs:
  bump-and-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Bump patch version
        run: python version_bump.py

      - name: Commit version bump
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add passworder/__init__.py
          git commit -m "Bump patch version [skip ci]" || echo "No changes to commit"

          git push "https://x-access-token:${TOKEN}@github.com/LukachuPro88/Passworder.git" HEAD:main-clean